### PR TITLE
Break things (followup from #166)

### LINKED ISSUE #167: A case against Promise swallowing
I'd like to make a few points about promise swallowing and how it is actually a harmful feature.

# It breaks `map`
`map` should follow some laws
  1. `f.map(g).map(f)` is equivalent to `f.map(compose(f,g))`
  2. `f.map(d => d)` is equivalent to `f`

Now let's try those laws out with promises

```js
const filter = stream('');
// assume the results are of form {content: Result[]}
const getResults = f => fetch(`${baseurl}/search?q=${f}`);
const results1 = filter
.map(getResults)
.map(prop('content'))

const results2 = filter
  .map(compose(prop('content'), getResults);

isEqual(results1, results2) // false
```

Promise swallowing actually makes it unsafe to refactor `map` using the mathematical laws it's supposed to follow.

# It breaks ordering

Imagine the same example as above

```js
const filter = stream('');
// assume the results are of form {content: Result[]}
const getResults = f => fetch(`${baseurl}/search?q=${f}`);

const results = filter
  .map(getResults)
  .map(prop('content'))

flyd.on(drawDOM, results);
document.querySelector('input.filter').addEventListener('input', filter);
```

Since the code handling promises in flyd is just
```js
p.then(s);
```
No ordering is guaranteed. So if I quickly write some filter like: 'res', then 3 promises are generated and they can be resolved in any order, the stream will always contain the last resolved promise.

# How do we fix these issues

It's simple, remove promise swallowing in favour of a `fromPromise` method

let's take the same example and rewrite it using the `fromPromise` helper

```js
const filter = stream('');
const getResults = f => fetch(`${baseurl}/search?q=${f}`);

const results = filter
  .pipe(chain(compose(fromPromise, getResults)))
  .map(prop('content'))

flyd.on(drawDOM, results);
document.querySelector('input.filter').addEventListener('input', filter);
```

Now what has changed?

1. We're no longer breaking `map`
2. Ordering is guaranteed since we're always generating a new stream and chain stops listening to the old stream as soon as a new one is generated.

### PR DESCRIPTION
**Pull request by nordfjord**
This will resolve #167 

And remove the functionality deprecated by #166 

this means

1. flatMap is no longer available as a module (use `flyd.chain` instead)
2. Promise swallowing is removed

### CODE REVIEW

**Comment by nordfjord** [comment]
@paldepind Are you ready to break things?

**Comment by StreetStrider** [comment]
Time for `v0.3`.

**Comment by c-dante** [comment]
Does this mean we can also close #37?

**Comment by paldepind** [comment]
@nordfjord I'm ready 😄 I'll take a good look this weekend!

**Comment by paldepind** [comment]
This looks good to me 🎉

**Comment by paldepind** [comment]
@StreetStrider 

> Time for v0.3.

What about releasing this as `v1.0.0`?

**Comment by StreetStrider** [comment]
@paldepind If you ask my opinion, I would like we all to investigate end stream related issues, mostly #116 and cast @c-dante @nordfjord, and think about how to signalize errors as well. #35 #164

I also wanted to pull up an deferred emitting discussion, but havent enough «meat» to start that discussion. You see, when you do `Promise.resolve(17).then(…)` execution is asynchronous (even in example, where result is already in). I think observable libary should follow that behavior for better guarantees for programmer, but flyd is special in that way and very-very syncronous by its nature. This is a topic for another discussion.

Last several months I was developing some build system, where flyd plays the same role that node streams plays in gulp. I'm ok with flyd, but I was forced to solve some very specific tasks, like async stream resolving, promise—stream, stream—promise bridges, value caching/backpessure. Some of them are definitely outside flyd's scope, but due solving them I was thinking that flyd is not ready for v1 yet, and I personally would love some time for changes to occur before things become more stable.

**Pull request merged**
