### PR TITLE
Add .eslintrc file

### PR DESCRIPTION
**Pull request by danigb**
- Added a .eslintrc files with rules copied from Ramda project (with slight modification to allow ++ and -- operators) 
- Modified the source code (of the library, modules and tests) to adapt them to the linter rules (mostly unused vars errors and spaces and indentation problems). 
- Add a `test-all` script to package.json that run all test (including the ones from modules) and check the js style. Run it with `npm run test-all`

### CODE REVIEW

**Comment by danigb** [comment]
Hi, 

I really like your library! I love the minimalistic approach. I started to study the code (I've added this eslintrc file to remove warnings from my editor), and I think for newcomers like me it would help (in order to understand the code) add jsdoc to the functions. 

Also, with jsdoc documentation it will be possible to auto-generate the API documentation (almost exactly to what you have in your README). Notice that I'm talking about documenting functions (not the code inside them).

Would you accept a PR with jsdoc added to index.js code?

**Comment by paldepind** [comment]
Hello. I am happy that you like it. 

Thank you for this PR. This is a really nice addition.

I agree that jsdoc documentation whould benefit many people. I'd appreciate such a PR as well :smile:

**Comment by danigb** [comment]
As I can see, travis is failing...

**Comment by danigb** [comment]
I'm glad you like the PR! Unfortunately travis is failing...

**Comment by paldepind** [comment]
Odd. The test timed out on Node 0.10. The tests runs fine for me. It might be a problem with Travis. I am restarting the test.

**Comment by paldepind** [comment]
Rerunning the tests did the trick. Again, thank you for the PR.

**Comment by tinchoz49** [comment]
this is a great idea for the snabbdom project too! :+1:

**Comment by danigb** [comment]
Great, thanks! If I get some time, I'll do it for snabbdom. Currently I'm trying to add some docs to flyd code. PR cooming soon.
Saludos

**Pull request merged**
