### PR TITLE
README: add flyd-droprepeats

### PR DESCRIPTION
**Pull request by raine**
I think the API is kind of weird right now, suggestions welcome.

### CODE REVIEW

**Comment by paldepind** [comment]
Nice! :+1: Thank you.

**Comment by paldepind** [comment]
I have released version 0.1.14 with this PR :)

**Comment by ericgj** [comment]
@raine  do you need `dropRepeatsWith` for a real use case?  If not, why not just export `dropRepeats` (i.e. strict eq) for now?  Thanks for this, by the way...

**Comment by raine** [comment]
I needed it for this https://github.com/raine/flyd-keyboard/blob/master/index.js#L4-L31

If you have a better implementation in mind, please share.

**Comment by ericgj** [comment]
Ah, right - I can see how strict equality would be pretty rare actually esp. with UI-generated data.  What about renaming it `dropWhere` -- and if you really wanted strict eq then you could do `dropWhere( R.identical, stream)`   ?

**Comment by raine** [comment]
How about getting `R.equals` behavior from some module and just using that in `dropRepeats(s)`?

**Comment by ericgj** [comment]
or what about a simple wrapper around
```js
const drop$ = flyd.scan( (prev,cur) => eq(prev,cur) ? prev : cur,  null, source$);
```

**Comment by raine** [comment]
I don't think I understand how that would work.

https://github.com/raine/flyd-droprepeats/issues/2

**Pull request merged**
